version: '3.5'

services:

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: 'rabbitmq_local'
    hostname: localhost
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - enqueuer-service
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: "/virtual_host_local"

networks:
  enqueuer-service:
    name: enqueuer-service
