version: '3.5'

services:

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: 'rabbitmq_local'
    hostname: localhost
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - enqueuer-service
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: "/virtual_host_local"

  sales-db-local:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_DB: "sales-db"
      POSTGRES_USER: "sales_user"
      POSTGRES_PASSWORD: "sales_password"
    ports:
      - "5442:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data2
    container_name: "sales-db-local"
    networks:
      - enqueuer-service

networks:
  enqueuer-service:
    name: enqueuer-service

volumes:
  postgres-data:
    external: false
