version: '3.5'

services:

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    hostname: my-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - enqueuer-service
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

networks:
  enqueuer-service:
    name: enqueuer-service
